### ISSUE TITLE
missing context and capability checks in webservice

### ISSUE THREAD

**Issue by danmarsden** [cli-ish/moodle-local_webshell#1]
https://github.com/cli-ish/moodle-local_webshell/blob/main/classes/external/run.php#L82

Please see here for more info:
https://moodledev.io/docs/4.4/apis/subsystems/external/writing-a-service#context-and-capability-checks

**Comment by cli-ish** [comment]
Hey @danmarsden,

glad to see you here. is the definition here: https://github.com/cli-ish/moodle-local_webshell/blob/main/db/services.php#L35 not enough ?

**Comment by cli-ish** [comment]
@danmarsden is there a specific reason why moodle allow defines such as https://github.com/cli-ish/moodle-local_webshell/blob/main/db/services.php#L35 even when its not checked? is it only for transparency in the webservice overview?

**Comment by danmarsden** [comment]
no. :-)

**Comment by danmarsden** [comment]
sorry - hit enter too quick....

the info in the services.php file is for informational purposes (eg in the webservices overview you mention.)
